# Generated by Django 2.0.2 on 2019-06-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='titile',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
