# Generated by Django 2.0.2 on 2019-06-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_titile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='titile',
            new_name='title',
        ),
    ]
